<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="CSCO-W-PF32ZV1R" failures="1" tests="4" name="getCustomerTest" time="4.891" errors="0" timestamp="2021-10-09T16:53:04 IST">
  <testcase classname="com.java.qa.sccm.test.LoginTest" name="loginTestValidation" time="2.69"/>
  <testcase classname="com.java.qa.sccm.test.GetCustomerDataTest" name="validateGetCustomer" time="0.707"/>
  <testcase classname="com.java.qa.sccm.test.GetCustomerDataTest" name="validateGetCustomer" time="0.634"/>
  <testcase classname="com.java.qa.sccm.test.GetCustomerDataTest" name="validateGetCustomer" time="0.617">
    <failure type="java.lang.AssertionError" message="expected [5002] but found [5003]">
      <![CDATA[java.lang.AssertionError: expected [5002] but found [5003]
at com.java.qa.sccm.test.GetCustomerDataTest.validateGetCustomer(GetCustomerDataTest.java:82)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- validateGetCustomer -->
</testsuite> <!-- getCustomerTest -->
