<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="CSCO-W-PF32ZV1R" failures="2" tests="4" name="Update Customer Test" time="5.181" errors="0" timestamp="2021-10-09T16:55:30 IST">
  <testcase classname="com.java.qa.sccm.test.LoginTest" name="loginTestValidation" time="2.484"/>
  <testcase classname="com.java.qa.sccm.test.UpdateCustomerTest" name="updateCustomer" time="1.272"/>
  <testcase classname="com.java.qa.sccm.test.UpdateCustomerTest" name="updateCustomer" time="0.612">
    <failure type="java.lang.AssertionError" message="expected [customer_id cannot be empty] but found [Customer Resource Not Found]">
      <![CDATA[java.lang.AssertionError: expected [customer_id cannot be empty] but found [Customer Resource Not Found]
at com.java.qa.sccm.test.UpdateCustomerTest.updateCustomer(UpdateCustomerTest.java:85)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- updateCustomer -->
  <testcase classname="com.java.qa.sccm.test.UpdateCustomerTest" name="updateCustomer" time="0.608">
    <failure type="java.lang.AssertionError" message="expected [Invalid customer_id] but found [Customer Resource Not Found]">
      <![CDATA[java.lang.AssertionError: expected [Invalid customer_id] but found [Customer Resource Not Found]
at com.java.qa.sccm.test.UpdateCustomerTest.updateCustomer(UpdateCustomerTest.java:90)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- updateCustomer -->
</testsuite> <!-- Update Customer Test -->
